# Spring
spring:
    application:
    name: application-design

    # Hibernate ddl auto
    jpa:
        hibernate:
            ddl-auto: create-drop
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true

# Server
server:
    port: 8080
    compression.enabled: true
    compression.mime-types: application/json,application/xml,text/html,text/xml,text/plain
